# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY backend/ .

# Expose the application port
EXPOSE 5001

# Start the Node.js application
CMD ["npm", "start"]
